version: "3"

services:
    web:
        container_name: web
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
    app:
        container_name: app
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8082:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8083:80"
        container_name: phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: db
            PMA_USER: phpmyadmin
            PMA_PASSWORD: phpmyadmin