version: "3"

services:
    cms-web:
        container_name: cms-web
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - cms-app
    cms-app:
        container_name: cms-app
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - cms-db
    cms-db:
        image: mysql
        restart: always
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8082:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: cms-db
    cms-phpmyadmin:
        image: phpmyadmin
        ports:
            - "8083:80"
        container_name: cms-phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            PMA_HOST: cms-db
            PMA_USER: root
            PMA_PASSWORD: root